[package]
name = "autograd"
version = "0.7.0"
authors = ["perrier1034 <janne.dc.ib.sa@gmail.com>"]

repository = "https://github.com/raskr/rust-autograd"
keywords = ["numerics", "machine-learning", "ndarray", "multidimensional", "neural-network"]
license-file = "LICENSE"
readme = "README.md"
description = "Tensors and computation graphs in Rust mimicking TensorFlow and Theano"
documentation = "https://docs.rs/autograd/"

[dependencies]
rand = "0.3.15"
ndarray = { version = "0.10.11", features = [] }
glob = "0.2"
blas-sys = { version = "0.6", optional = true, default-features = true, features = ["openblas"] }
rayon = "0.8.2"

[lib]
name = "autograd"
path = "src/lib.rs"

[[example]]
name = "mlp_mnist"
path = "examples/mlp_mnist.rs"

[[example]]
name = "lstm_lm"
path = "examples/lstm_lm.rs"

[features]
default-features = ["blas"]
blas = ["ndarray/blas", "blas-sys"]
